# Generated by Django 3.1.3 on 2020-11-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfiction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='fandoms',
            field=models.ManyToManyField(to='fanfiction.Fandom'),
        ),
    ]
