# Generated by Django 3.1.3 on 2021-08-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfiction', '0002_work_fandoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='comleted',
            new_name='completed',
        ),
    ]
