export const RECIEVED_WORKS = 'RECIEVED_WORKS';
export const RECIEVED_CATEGORIES = 'RECIEVED_CATEGORIES';
export const RECIEVED_FANDOMS_BY_CATEGORY = 'RECIEVED_FANDOMS_BY_CATEGORY';
export const RECIEVED_WORKS_BY_FANDOM = 'RECIEVED_WORKS_BY_FANDOM';